from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3005", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/v1/query")
async def mock_query(req: dict):
    return {
        "answer": "This is a mock answer generated by the Stealth Dashboard Mock Server. Project A will reduce the Q3 budget by approximately 15% due to aggressive reallocation of cloud resources.",
        "chunks": [
            {
                "rank": 1,
                "chunk_id": "chunk_001",
                "source": "Q3_Financials.pdf",
                "content": "The Q3 budget adjustments specifically account for Project A's cloud reallocation...",
                "access_level": "internal",
                "distance_score": 0.98,
                "keyword_score": 0.5,
                "rrf_score": 0.04,
                "weighted_score": 0.88,
                "page": 14
            },
            {
                "rank": 2,
                "chunk_id": "chunk_002",
                "source": "Project_A_Specs.pdf",
                "content": "Project A requires an initial scale-up before minimizing steady-state burn rate.",
                "access_level": "internal",
                "distance_score": 0.85,
                "keyword_score": 0.4,
                "rrf_score": 0.03,
                "weighted_score": 0.75,
                "page": 2
            }
        ],
        "graph_path": ["classify", "retrieve", "grade_documents", "generate"],
        "relevance_ratio": 1.0,
        "rewritten_query": None,
        "query_type": "simple",
        "graph_entities": [],
        "graph_traversal_path": []
    }

@app.post("/v1/ingest")
async def mock_ingest(req: dict):
    return {
        "chunks_created": 0,
        "source": "mock_upload.pdf",
        "job_id": "job_12345",
        "status": "processing"
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
